spring.application.name=event-hub-academy

# Indirizzo del database PostgreSQL esposto sulla porta 5432 del container Docker
spring.datasource.url = jdbc:postgresql://localhost:5432/eventhub
# Credenziali di accesso (presenti in docker-compose.yml)
spring.datasource.username = eventhub_admin
spring.datasource.password = password123
# Driver ufficiale per consentire a Spring di comunicare con PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Specifica a Hibernate il dialetto SQL di Postgres per tradurre correttamente i comandi
spring.jpa.database-platform = org.hibernate.dialect.PostgreSQLDialect
# Crea o aggiorna le tabelle in automatico basandosi sulle classi @Entity, senza cancellare i dati esistenti
spring.jpa.hibernate.ddl-auto = update
# Stampa in console tutte le query in modo leggibile
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql=true


# Cambia la porta di Spring Boot per evitare il conflitto con Adminer di Docker
server.port=8081
